katzlabbrandeis/blech_clust

- utils/blech_process_utils.py
- utils/clustering.py
- Add extract_waveforms_hannah function for rolling threshold during spike extractions
- Update blech_process_utils to correctly index energy and amplitude
> Extract waveforms hannah

- blech_exp_info.py
- blech_process.py
- utils/blech_process_utils.py
Previously, setting the param to True did nothing since code handling the setting was not updated to new class structure
> bug fixes for waveform_classifier "throw_out_noise" setting

- emg/_archive/emg_process_comparison.py
- emg/emg_BSA_segmentation.py
- emg/emg_BSA_segmentation_plot.py
Fix issues with uneven trial handling in emg processing
> Emg updates

- _experimental/raw_dat_corr/raw_channel_correlation_test.py
- _experimental/raw_dat_corr/remove_rawdata_and_sorted_units.py
- blech_clust.py
- params/sorting_params_template.json
- utils/qa_utils.py
Simple code addition to blech_clust.py to calculate correlations between raw data to check for bridged channels.
> 80 test for bridges channels

- README.md
- blech_clust.py
- blech_clust_pre.sh
- blech_process.py
- params/sorting_params_template.json
- pipeline_testing/prefect_pipeline.py
- utils/blech_process_utils.py
- utils/blech_spike_features.py
- utils/blech_waveforms_datashader.py
blech_clust now writes the parallelizing bash scripts to the data directory
blech_run_process.sh in blech_clust directory simply calls these files.
This was, bash steps are not longer chained to be run in strict sequence after blech_clust
> 88 bash parallel step should take directory as input

- blech_units_plot.py
- utils/blech_process_utils.py
> Add subplots for ISI dist and spike-counts over time

- emg/emg_BSA_segmentation.py
- emg/emg_BSA_segmentation_plot.py
Update handling of indices for reshaping all trials according to laser_conditions and tastes
> Fix digin numbering

- blech_run_process.sh
- utils/blech_process_utils.py
1. Add blech_run_process.sh file that I forgot to add for merge https://github.com/abuzarmahmood/blech_clust/commit/ea8e3cfa3f4192c0a6b07589c1b10de012976064, when the bash step was detached from using blech.dir
2. Fix issues with plotting related to classifier output
> Add blech_run_process.sh file + fix classifier plot issues.

- README.md
Fixes for #110  
- Confirmed that `Order of Operations` in README aligns with flowchart
- Moved `Order of Operations` higher in README
> 110 update readme to align with latest code

- blech_post_process.py
- utils/blech_post_process_utils.py
- utils/blech_process_utils.py
> [FIX] Fix issues with HDF5 handling during post-process

- blech_clust.py
- blech_post_process.py
- utils/cluster_stability.py
For each clustering solution on every electrode:
We generate a hierarchical clustering plot to more clearly visualize the underlying features of each cluster:
> Hierarchical clustering plot to better assess cluster stability

- blech_overlay_psth.py
- Fix blech_overlay_psth to use params from params_dict
- Add heatmaps for output of every unit
> 119 overlay psth add heatmaps

- blech_clust.py
Laser trials will show up as a partially transparent axvline.
> Add plot with dig-in order to QA_output dir

- README.md
- blech_channel_profile.py
- blech_clust.py
- blech_run_process.sh
- utils/read_file.py
Most of the edits I've been making, minus a few that were more likely to cause downstream issues pending testing.
> Bat safer edits

- utils/blech_process_utils.py
HOTFIX for no plot issue in blech_post_process
> Remove agg backend from blech_process_utils

- _archive/blech_process_func.py
- additional_analyses/LFP_analysis/_old/LFP_Spectrogram_Stone.py
- pipeline_testing/cut_emg_trials.py
- utils/blech_process_utils.py
Screened out the old np.int calls
> 155 change npint to int

- README.md
- blech_clust_post.sh
Update order of operations to have QA steps run after make_arrays
> 176 blech run qa error

- blech_exp_info.py
- blech_run_process.sh
Adds a bit of code that allows blech_run_process.sh to find and overwrite (if desired) results.log.
Also slightly tweaks some of the interface text in belch_exp_info.py, just to try to make a more consistent format. No functional changes, purely aesthetic.
> 171 make faq with deleting resultslog for blech run processpy

- blech_clust.py
- blech_common_avg_reference.py
- blech_exp_info.py
- blech_make_arrays.py
- blech_make_psth.py
- blech_overlay_psth.py
- blech_palatability_identity_setup.py
- blech_post_process.py
- blech_process.py
- blech_units_plot.py
- emg/emg_filter.py
- emg/emg_freq_post_process.py
- emg/emg_freq_setup.py
- emg/emg_local_BSA_execute.py
- emg/emg_local_STFT_execute.py
- emg/gape_QDA_classifier/get_gapes_Li.py
- params/dependency_graph.json
- pipeline_testing/prefect_pipeline.py
- utils/blech_utils.py
- utils/qa_utils/drift_check.py
- utils/qa_utils/unit_similarity.py
Will close issue #45 if successfully merged
> 45 workflow management -- only run next step if dependencies have been fulfilled

- blech_clean_slate.py
- pipeline_testing/prefect_pipeline.py
- pipeline_testing/test_data_handling/prep_data_info.py
Updates capture error in #206 
prefect pipeline swaps out info and electrode_layout files to imitate datasets with emg only, spike only, and emg + spike datasets
> 209 no emg dataset for testing can simply be done by using a different exp info file

- utils/ephys_data/BAKS.py
- utils/ephys_data/convenience_scripts/region_spectrogram_plot.py
- utils/ephys_data/ephys_data.py
- utils/ephys_data/lfp_processing.py
- utils/ephys_data/project.log
- utils/ephys_data/tests/ephys_data_implement.py
- utils/ephys_data/tests/ephys_data_testing.py
- utils/ephys_data/tests/lfp_artifact_test.py
- utils/ephys_data/tests/region_spikes_test.py
- utils/ephys_data/tests/stft_test.py
- utils/ephys_data/visualize.py
Roadmap should include usage instructions for ephys data
> Add ephys_data as a utility

- utils/ephys_data/ephys_data.py
Add functionality to calculate palatability in ephys data
> Palatability calc

- blech_exp_info.py
- utils/ephys_data/ephys_data.py
Add
- emg muscle region
- virus region
- opto fiber region
> 228 add opto + emg regions to info files

- .gitignore
- blech_clust.py
- blech_common_avg_reference.py
- blech_post_process.py
- pipeline_testing/prefect_pipeline.py
with `aider` and `claude-sonnet-3.5`
> Refactor test2

- utils/ephys_data/ephys_data.py
- utils/ephys_data/lfp_processing.py
autogenerated using `aider` + `claude-sonnet-3.5`
> 248 add ephs data usage details to readmewiki

- blech_clust.py
- utils/read_file.py
But not sure why dig_in_ints are being compared if not to discard empty ones detected by info file
https://github.com/katzlabbrandeis/blech_clust/blob/3cc308e47306fa9047b07b19bbe4b6ac5ad5ff51/utils/read_file.py#L74
> Fix dig in handling bug

- requirements/pip_requirements_base.txt
- utils/qa_utils/elbo_drift.py
- Saves calculated ELBO and changepoint locations as dataframes in an artifact dir (size is ~50kb so can be easily copied)
- Creates plots of ELBO for each taste
- ![KM45_5tastes_210620_113227_new_taste_0_trial_change_elbo](https://github.com/user-attachments/assets/38b453d6-4701-4d40-8cb5-dbf7336a4523)
- Creates plots of ELBO across tastes
-
> 271 drift detection using changepoint on across trial pca

- blech_clust.py
- blech_exp_info.py
- blech_make_arrays.py
- params/dependency_graph.json
- utils/blech_utils.py
- utils/read_file.py
- Create `DigInHandler` that is run during `blech_exp_info.py` and records relevant info (including pulse starts and ends) and writes them to file `dig_in_frame.csv`
- `dig_in_frame.csv` is then used in `blech_clust.py` and `blech_make_arrays.py` rather than reloading dig-ins
> 270 improve dig in name handling + handling unused digins

- params/_templates/sorting_params_template.json
- utils/qa_utils/unit_similarity.py
- **feat: Add similarity matrix visualization with raw and thresholded panels**
- **feat: Enhance unit similarity matrix plot with improved title and labels**
- **feat: Add waveform counts to unit similarity violations output**
- **feat: Add similarity_waveform_count_cutoff parameter to sorting params template**
- **feat: Add waveform count cutoff check to unit similarity output**
- **Update waveform_count_cutoff handling**
> 303 similarity matrix plot for units similarity

- pipeline_testing/prefect_pipeline.py
- **feat: Integrate RNN test into prefect pipeline with new task and flow**
- **fix: Resolve undefined data_type in emg_only_test function**
- **refactor(pipeline): remove RNN test functionality**
> 320 add infer rnn ratespy to prefect pipeline for testing

- params/_templates/blechrnn_params.json
- utils/infer_rnn_rates.py
- utils/makeRaisedCosBasis.py
- Removed `--override_config` argument and simplified configuration loading.
- The script now default loads configuration from a file and overrides only if arguments are provided.
- Improved clarity and maintainability of the script by removing redundant checks and prints.
> refactor(infer-rnn-rates): simplify argument handling and config loading

- blech_units_characteristics.py
- Added test mode for easier debugging
- Improved data filtering by cutting data based on `psth_params['durations']`
- Fixed laser tuple conversion using `literal_eval`
- Enhanced plots:
- Increased figure width for better visualization
- Added laser condition highlighting in plots
- Improved legend positioning and formatting
- Changed scatter markers from '|' to 's' and increased size for better visibility
- Sorted laser conditions for consistent ordering
> update units characteristics plotting

- blech_process.py
- utils/blech_process_utils.py
- **refactor(utils): modify classifier plotting and feature extraction methods**
- **refactor(classifier): update noise reduction and feature extraction process**
- **fix(process): update spike data handling and print statements in classification workflow**
> 407 plot noise scatter even if throw out noise is true

- utils/blech_process_utils.py
- utils/blech_waveforms_datashader.py
- **feat: Add envelope plot with mean and standard deviation to waveform visualization**
- **feat: Add waveform envelope plot function to utils module**
- **fix: Pass max and min values to y_transform function to resolve undefined variable**
> 402 feature request envelope view of waveforms from run process

- blech_post_process.py
- blech_process.py
- utils/blech_post_process_utils.py
- utils/blech_process_utils.py
- utils/clustering.py
- **feat(spike-processing): add MAD value handling to spike processing**
- **fix(process): improve reliability of MAD value writing and update test flag**
- **fix(metadata): add backoff loop for layout writing**
- **feat(post_process): add SNR calculation and storage for unit descriptions**
- **fix(blech_process): correct test_bool flag value**
- **feat(utils): add SNR calculation to unit descriptor**
- **fix(post-processing): improve sorted units handling and auto-processing logic**
> 233 add snr to unit descriptor

- blech_process.py
- blech_units_plot.py
- utils/blech_process_utils.py
- utils/blech_waveforms_datashader.py
feat(plotting): enhance spike visualization with threshold
- Added threshold value handling and storage in `blech_process.py`.
- Modified `blech_units_plot.py` to:
- Retrieve threshold values from layout for plot annotations.
- Adjust plot titles and annotations with additional information such as SNR.
- Include threshold lines in waveform plots for better visualization.
- Updated `waveforms_datashader` function signature for improved readability.
refactor(plot): improve threshold handling and code formatting
- Ensure proper extraction of threshold value using `.values[0]` in `blech_units_plot.py`.
- Use `.2f` for formatting SNR value in the plot title.
- Update function call formatting for better readability.
- Simplify threshold line drawing in `blech_waveforms_datashader.py` by …
> feat(plotting): enhance spike visualization with threshold

- README.md
- blech_post_process.py
- blech_units_plot.py
- utils/blech_post_process_utils.py
Refactored the neural data processing script into modular functions with improved organization and documentation.
- Restructured the monolithic script into well-defined functions with clear responsibilities:
- `setup_environment()`: Handles initialization and environment setup
- `prepare_output_directory()`: Creates clean output directories
- `load_units_data()`: Loads and processes HDF5 data
- `plot_unit_summary()`: Generates comprehensive plots for a single unit
- `process_all_units()`: Processes all neural units
- `save_individual_plots()`: Saves separate waveform visualizations
- `main()`: Orchestrates the entire workflow
- Added detailed docstrings to each function explaining parameters and return values
- Simplified the module-level docstring while preserving key information
- …
> refactor: Modularize blech_units_plot.py into functions for improved code organization

- .github/workflows/pytest_workflow.yml
- blech_units_plot.py
- utils/blech_post_process_utils.py
- utils/blech_process_utils.py
- Use functions generated using refactored code in `blech_units_plots.py` to create plots in `blech_process.py`
> use_units_plot_for_blech_process

- utils/grade_dataset.py
- Removed redundant code for test condition setup, enhancing clarity and maintaining the focus on neural properties under the laser condition '(0, 0)' exclusively.
- Improved the extraction of relevant columns by filtering data based on laser conditions, aligning grading precision.
- Maintained functionality while optimizing script readability and maintainability.
> refactor(grading): improve handling of laser conditions and streamline data prep

- emg/emg_freq_post_process.py
- emg/emg_freq_setup.py
- pipeline_testing/prefect_pipeline.py
- **feat(emg): enhance emg_freq_setup with data export and processing**
- **refactor(emg): enhance post-processing and data handling for EMG analysis**
> 496 add script to convert emg processing outputs back to arrays as with older versions of blech clust

- README.md
- tests/test_ephys_data.py
This PR addresses issue #510 by creating a comprehensive pytest test suite for the `ephys_data.py` module.
- **21 comprehensive tests** covering core functionality of the `ephys_data` class
- **3 test classes** organized by functionality:
- `TestEphysDataCore`: Core functionality and static methods
- `TestEphysDataIntegration`: Integration tests and workflows  
- `TestEphysDataStaticMethods`: Focused static method testing
- ✅ STFT calculation with various parameters
- ✅ Convolution-based firing rate calculation
- ✅ BAKS (Bayesian Adaptive Kernel Smoother) firing rate calculation
- ✅ Array conversion utilities
- ✅ HDF5 node removal
- ✅ Parallel processing functionality
- ✅ Class initialization with/without data directory
- ✅ HDF5 file detection (single, multiple, none)
- ✅ Default …
> Add comprehensive pytest test suite for ephys_data.py
